name: Documentation (staging)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  documentation:
    runs-on: ubuntu-latest
    environment: staging
    env:
      GATSBY_UNLEASH_URL: ${{vars.UNLEASH_URL}}
      GATSBY_UNLEASH_APP_NAME: ${{vars.UNLEASH_APP_NAME}}
      GATSBY_UNLEASH_CLIENT_KEY: ${{vars.UNLEASH_CLIENT_KEY}}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          check-latest: true
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i

      - name: Generate "API Documentation" page
        run: pnpm i -g esbuild; pnpm generate; pnpm run generate-api-docs

      - name: Build
        run: pnpm build
        
      - uses: botpress/gh-actions/deploy/s3@v2
        if: github.ref == 'refs/heads/master'
        with:
          aws-role: ${{ secrets.AWS_DOCUMENTATION_UPLOAD_ROLE }}
          source: ./packages/documentation/public
          destination: s3://${{ secrets.AWS_DOCUMENTATION_BUCKET_NAME }}/docs
          cloudfront-distribution-id: ${{ secrets.AWS_DOCUMENTATION_CLOUDFRONT_DISTRIBUTION_ID  }}
          cloudfront-invalidation-prefix: '/docs/*'
